import type { Metadata } from "next";
import Header from "../components/Header";

export const metadata: Metadata = {
  title: "App Ing Economica",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Header
        title="Interes y Amortizacion"
        routes={[
          {
            name: "interes simple-compuesto",
            href: "/amortizacion",
          },
          {
            name: "Amortizacion americana",
            href: "/amortizacion/amortizacion-americana",
          },
          {
            name: "Amortizacion frances",
            href: "/amortizacion/amortizacion-frances",
          },
          {
            name: "Amortizacion alemana",
            href: "/amortizacion/amortizacion-alemana",
          },
        ]}
      />
      <div>{children}</div>
    </div>
  );
}
